name: Generate Javadoc

on:
  push:
    branches:
      - main

jobs:
  generate-and-commit-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Commit Javadoc
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f ./src
          git commit -m "Update Javadoc [skip ci]" || echo "No changes to commit"
          git push
